services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: bhandara-server
    container_name: bhandara-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - bhandara-network

networks:
  bhandara-network:
    driver: bridge
